const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const doc = new PDFDocument();
const outputPath = path.join(__dirname, '../client/public/AceIt_Interview_Questions.pdf');

doc.pipe(fs.createWriteStream(outputPath));

doc.fontSize(24).fillColor('#0f172a').text('AceIt.AI Interview Question Guide', { align: 'center' });
doc.moveDown();
doc.fontSize(12).fillColor('#64748b').text('Master your technical interviews with these curated expert questions and answers.', { align: 'center' });
doc.moveDown(3);

const QA = [
  {
    role: "Software Engineering",
    qa: [
      { q: "Explain the distinction between process and thread.", a: "A process is an independent program in execution with its own memory space, while a thread is a subset of a process. Multiple threads within the same process share the same memory." },
      { q: "How does a hash map resolve collisions?", a: "Hash maps typically resolve collisions using either Chaining (storing a linked list at the bucket) or Open Addressing (probing for the next available slot)." },
      { q: "What is the Event Loop in Node.js?", a: "The Event Loop is a mechanism that handles asynchronous callbacks in a single-threaded environment, continuously checking the call stack and task queues." },
      { q: "Explain REST versus GraphQL.", a: "REST exposes multiple endpoints for different resources (can over/under-fetch). GraphQL exposes a single endpoint allowing clients to specify exact data shapes." }
    ]
  },
  {
    role: "Machine Learning",
    qa: [
      { q: "What is the bias-variance tradeoff?", a: "The balance between a model's ability to minimize errors on training data (low bias) vs generalize to unseen test data (low variance)." },
      { q: "Explain the Transformer architecture.", a: "It relies on self-attention mechanisms to process entire sequences simultaneously, allowing for parallelization and understanding token order via positional encoding." },
      { q: "How do you handle severe class imbalance?", a: "Techniques include oversampling (SMOTE), undersampling, or using class-weighted loss functions." }
    ]
  },
  {
    role: "Data Science",
    qa: [
      { q: "Explain P-value and Statistical Power.", a: "P-value is the probability of obtaining test results at least as extreme as observed assuming null hypothesis is true. Statistical Power is the probability of correctly rejecting a false null hypothesis." },
      { q: "How do you design a reliable A/B test?", a: "Formulate a clear hypothesis, select robust metrics, calculate sample size based on power, randomize cleanly, and avoid peeking prematurely." }
    ]
  }
];

QA.forEach(section => {
  doc.fontSize(18).fillColor('#0d9488').text(section.role);
  doc.moveDown();
  
  section.qa.forEach((item, index) => {
    doc.fontSize(12).fillColor('#0f172a').font('Helvetica-Bold').text(`Q${index + 1}: ${item.q}`);
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#475569').font('Helvetica').text(`Answer: ${item.a}`);
    doc.moveDown();
  });
  doc.moveDown(2);
});

doc.fontSize(10).fillColor('#94a3b8').text('Generated by AceIt.AI | The ultimate technical interview simulator', { align: 'center', bottom: 50 });

doc.end();
console.log('PDF generated at ' + outputPath);
